using System;
using System.Collections.Generic;
using System.Linq;

namespace Taijitan_Yoshin_Ryu_vzw.Models.Domain {
    public class Trainingsmoment {
        #region Properties
        public int Id { get; set; } //Autogenerated
        public int DagNummer { get; set; }
        public string DagNaam { get; set; }
        public string BeginUur { get; set; }
        public string EindUur { get; set; }
        #endregion

        #region Collections
        public virtual ICollection<FormuleTrainingsmoment> FormuleTrainingsmomenten { get; private set; }
        public IEnumerable<Formule> Formules => FormuleTrainingsmomenten.Select(f => f.Formule);
        #endregion

        #region Constructors
        public Trainingsmoment() {
            FormuleTrainingsmomenten = new HashSet<FormuleTrainingsmoment>();
        }

        public Trainingsmoment(int dagNummer, string dagNaam, string beginUur, string eindUur) : this() {
            DagNummer = dagNummer;
            BeginUur = beginUur;
            EindUur = eindUur;
            DagNaam = dagNaam;
        }
        #endregion

        #region Methods        
        public DateTime geefDatumBeginUur() {
            return geefDatumUur(BeginUur);
        }

        public DateTime geefDatumEindUur() {
            return geefDatumUur(EindUur);
        }

        private DateTime geefDatumUur(string uur) {
            return DateTime.ParseExact(uur, "H:mm", null, System.Globalization.DateTimeStyles.None);
        }
        #endregion
    }
}
